### ISSUE TITLE
[__NSCFString hasPrefix:]: nil argument Raw Text

### ISSUE THREAD

**Issue by weipinglii** [youzan/YouzanMobileSDK-iOS#1]
Fatal Exception: NSInvalidArgumentException-[__NSCFString hasPrefix:]: nil argument Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
3 | CoreFoundation | -[__NSCFString hasPrefix:]
4 | ting | YZSMCacheManager.m line 357__38-[YZSMCacheManager writeCache:toPath:]_block_invoke
5 | libdispatch.dylib | _dispatch_call_block_and_release
12 | libsystem_pthread.dylib | start_wqthread

**Comment by DeveloperPans** [comment]
请提供一下复现的步骤，以便我们排查问题 ： ）

**Comment by weipinglii** [comment]
没有找到复现的方式，看crashlytics里的记录发现的，出现概率并不是很高

**Comment by DeveloperPans** [comment]
好的，我们会持续跟进，后续还有类似情况请继续反馈。
