### ISSUE TITLE
6.4.3 release版本有bug

### ISSUE THREAD

**Issue by kevin930119** [youzan/YouzanMobileSDK-iOS#10]
当我用新版sdk时，YZWebView初始化为WKWebView，那么给YZSDK传递登录态token后，还是会给我发送需要登录的通知，每次都是这样，但是当YZWebView初始化为UIWebView时，传递登录态token后就正常了，希望开发人员能够找一下这个原因。

**Comment by VajraSheng** [comment]
请更新至最新版本，若再有此问题请及时联系技术支持，谢谢~
