### ISSUE TITLE
使用pod安装的，模拟器一直崩溃dyld: Library not loaded: @rpath/YZSDKCore.framework/YZSDKCore

### ISSUE THREAD

**Issue by excsir** [youzan/YouzanMobileSDK-iOS#12]
在模拟器上跑不起来，一直报错
dyld: Library not loaded: @rpath/YZSDKCore.framework/YZSDKCore
  Referenced from: /Users/chao/Library/Developer/CoreSimulator/Devices/D5B5FFDD-F60A-4454-A30A-A5ECEBCA8ADF/data/Containers/Bundle/Application/2FCA84C5-FC80-4B50-A519-374BB2D517CE/CLMicroWork.app/Frameworks/YZBaseSDK.framework/YZBaseSDK
  Reason: no suitable image found.  Did find:
	/Users/chao/Library/Developer/CoreSimulator/Devices/D5B5FFDD-F60A-4454-A30A-A5ECEBCA8ADF/data/Containers/Bundle/Application/2FCA84C5-FC80-4B50-A519-374BB2D517CE/CLMicroWork.app/Frameworks/YZSDKCore.framework/YZSDKCore: no matching architecture in universal wrapper
	/Users/chao/Library/Developer/CoreSimulator/Devices/D5B5FFDD-F60A-4454-A30A-A5ECEBCA8ADF/data/Containers/Bundle/Application/2FCA84C5-FC80-4B50-A519-374BB2D517CE/CLMicroWork.app/Frameworks/YZSDKCore.framework/YZSDKCore: no matching architecture in universal wrapper
	/Users/chao/Library/Developer/CoreSimulator/Devices/D5B5FFDD-F60A-4454-A30A-A5ECEBCA8ADF/data/Containers/Bundle/Application/2FCA84C5-FC80-4B50-A519-374BB2D517CE/CLMicroWork.app/Frameworks/YZSDKCore.framework/YZSDKCore: no matching architecture in universal wrapper
	/Users/chao/Library/Developer/CoreSimulator/Devices/D5B5FFDD-F60A-4454-A30A-A5ECEBCA8ADF/data/Containers/Bundle/Application/2FCA84C5-FC80-4B50-A519-374BB2D517CE/CLMicroWork.app/Frameworks/YZSDKCore.framework/YZSDKCore: no matching architecture in universal wrapper
(lldb)

**Comment by VajraSheng** [comment]
问题已解决，请更新至6.4.8，谢谢~
