### ISSUE TITLE
6.4.8版本YZWebView缺少title属性

### ISSUE THREAD

**Issue by liuzhida33** [youzan/YouzanMobileSDK-iOS#13]
使用 6.4.8版本SDK并未发现YZWebView提供title属性，希望作者能够提供一下，感激不尽

**Comment by VajraSheng** [comment]
目前暂不考虑添加此属性，建议通过 [webView evaluateJavaScript:@"document.title" completionHandler:^(id  _Nullable response, NSError * _Nullable error) {}]; 的方式获取，谢谢
