### ISSUE TITLE
6.4.9 release版本有bug

### ISSUE THREAD

**Issue by kevin930119** [youzan/YouzanMobileSDK-iOS#14]
使用6.4.9版本的SDK，并且webView初始化为WKWebView，进入商品详情页，再随便打开一个新页面，调用goBack返回上一个网页时，会报错，-999的错误，如果webView初始化为UIWebView，那么就不会有这个问题。

**Comment by VajraSheng** [comment]
这边检查没有复现此问题，方便的话麻烦联系技术支持沟通下具体问题也方便我们持续改进，谢谢~
