### ISSUE TITLE
为什么没有i386？

### ISSUE THREAD

**Issue by fengning0901** [youzan/YouzanMobileSDK-iOS#2]
如题

**Comment by fengning0901** [comment]
如果可以麻烦把i386 x86_64 armv7 armv7s arm64都打进去，就三个架构在里面，有点不专业了。

**Comment by DeveloperPans** [comment]
i386是 32 位处理器模拟器的架构支持，iphone5以下的模拟器才用得到。为了减小包大小特意去除的。

用iphone5s及以上模拟器，或者真机调试即可。
