### ISSUE TITLE
使用 SDK v7.0.3 初始化 YZWebView 失败

### ISSUE THREAD

**Issue by ziiip** [youzan/YouzanMobileSDK-iOS#26]
SDK v7.0.3，CocoaPods 方式接入，填入了 appKey，初始化后，尝试初始化 YZWebView 遇到下面情况

![1605701599422](https://user-images.githubusercontent.com/8551909/99529303-87082780-29da-11eb-9ab9-de133bca50b9.jpg)

如图，初始化后，得到的是空的对象，请问如何解决？

**Comment by liuzhuoming** [comment]
同样的问题

**Comment by liuzhuoming** [comment]
@ziiip 解决问题了吗，我也遇到了同样的问题

**Comment by ziiip** [comment]
@liuzhuoming 更新最新的v7.0.5可以解决大部分情况的问题。可能需要等更加新的版本

**Comment by liuzhuoming** [comment]
我就是7.0.5啊

**Comment by ziiip** [comment]
我这边在 v7.0.5 版本上遇到的情况就很特殊了。不行就问他们技术吧。我现在已经将代码滚到 v6 版本了。

**Comment by cuncle** [comment]
初始化失败，一般是因为安全码校验失败。 
可以通过 SDK 提供的方法重新发起安全码校验。
iOS参考:https://github.com/youzan/YouzanMobileSDK-iOS/wiki/%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%977.x#%E5%BC%B1%E7%BD%91%E6%A0%A1%E9%AA%8C%E5%A4%B1%E8%B4%A5%E9%80%BB%E8%BE%91%E5%A4%84%E7%90%86
