### ISSUE TITLE
从微信回到自己App，如何判断是否支付成功？

### ISSUE THREAD

**Issue by wangrui460** [youzan/YouzanMobileSDK-iOS#5]
我是已经购买App开店，然后接的是原生App开发，因为支付页面必须是 h5 页面，进入h5支付页面，然后跳转微信支付，回来后怎么知道是否支付成功呢？或者说我跳转到微信支付后，用户并没有支付，然后手动调回App，那App怎么判断用户是否支付呢？

**Comment by DeveloperPans** [comment]
目前版本还没有支付回调。
不过我们正在开发中，下一个版本会提供支付成功的回调接口。

**Comment by wangrui460** [comment]
也就是说，现在支付成功或失败只能表现在h5页面中是吧

**Comment by wangrui460** [comment]
好的
