### ISSUE TITLE
集成有赞时候未收到登录的通知

### ISSUE THREAD

**Issue by yj9294** [youzan/YouzanMobileSDK-iOS#7]
YZWebViewNoticeDelegate中我实现了- (void)webView:(YZWebView *)webView didReceiveNotice:(YZNotice *)notice方法 但是就是没有收到YZNoticeTypeLogin登录请求，麻烦解决下

**Comment by DeveloperPans** [comment]
1. 检查 noticeDelegate = self 是否设置
